title_name = "Silent Hill: Downpour"
title_id = "4B4E0823" # KN-2083
hash = "7A3D5809776EE6AB" # default.xex
#media_id = "7D387D17" # Disc (USA, Europe): http://redump.org/disc/58138

[[patch]]
    name = "Unlock FPS"
    desc = "See note about framerate patches in the README. Camera movement slows down over 60 FPS."
    author = "illusion, Aphelion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x825c64c8
        value = 0x60000000
    [[patch.be8]]
        address = 0x82d20f83
        value = 0x01

[[patch]]
    name = "Disable FXAA & MLAA"
    desc = "Post-process anti-aliasing can significantly impact image sharpness and definition. This patch is particularly useful when using resolution upscaling or FSR."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82a04ba0 # SHGame.MLAAPostProcess
        value = 0x38600000 # li r3, 0x0
    [[patch.be16]]
        address = 0x82a1095f
        value = 0x6441 # cmpwi r8 0x64; beq 82a10970
    [[patch.be32]]
        address = 0x82a10964 # Engine.GlobalPostProcessSettings.ForceFXAA
        value = 0x39600000 # li r11, 0x0

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x829d342c
        value = 0x38a00010
