title_name = "Fable II" # 2
title_id = "4D5307F1" # MS-2033
hash = "43FFE5AFC5042DD2" # default.xex
#media_id = [
#    "0962B000", # Disc (USA, Europe) (Rev 1): http://redump.org/disc/42254
#    "768FC8D1", # Disc (Russia) (Rev 1):      http://redump.org/disc/90843
#    "6306C101", # Disc (Germany):             http://redump.org/disc/46610
#]

[[patch]]
    name = "60 FPS"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x82b9c69b
        value = 0x01

[[patch]]
    name = "1280x720 Resolution"
    desc = "Original resolution is 1120x720."
    author = "Margen67"
    is_enabled = false

    [[patch.be16]]
        address = 0x8238f3da
        value = 0x0500

[[patch]]
    name = "Disable MSAA (Multi-Sample Anti-Aliasing)"
    author = "Margen67"
    is_enabled = false

    [[patch.be8]]
        address = 0x8238f3bf
        value = 0x01
