title_name = "Crackdown 2 Demo"
title_id = "4D5388BF" # MS-35007
hash = "54F6EF3FCB37D4C2" # default.xex
#media_id = "22AFC3C2"

[[patch]]
    name = "Freeze Demo Timer"
    author = "Serenity"
    is_enabled = false

    [[patch.be32]]
        address = 0x82815380
        value = 0x60000000
