title_name = "Harm's Way"
title_id = "58410A70" # XA-2672
hash = "B599434564E4D7E1" # default.xex
#media_id = "336F22CD"

[[patch]]
    name = "Unlock FPS"
    desc = "See note about framerate patches in the README."
    author = "illusion, Margen67"
    is_enabled = false

    [[patch.be32]]
        address = 0x82d08d10
        value = 0x39600000
